import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <center className="p-2 m-2"><Link href={"/"}><button className="bg-green-500 text-white font-bold py-3 px-8 rounded-lg transition duration-400 hover:bg-white hover:text-black hover:border-green-500 hover:border-2">Home</button></Link>  
      <Link href={"/admin"}><button className="bg-green-500 text-white font-bold py-3 px-8 rounded-lg transition duration-400 hover:bg-white hover:text-black hover:border-green-500 hover:border-2">Admin</button></Link>  
      
      </center>
      


        {children}
      </body>
    </html>
  );
}
